# This config file is downloaded by users-service only

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/photo-app
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: PASSWORD
  jpa:
    hibernate:
      ddl-auto: update