server:
  port: 8012
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TanPhotoApp/configuration
          username:
          password:
          clone-on-start: true
          default-label: main