server:
  port: 8888

spring:
  application:
    name: config-server
    # This enables File System Backend
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TanPhotoApp/configuration
          username: tanlh
          password:
          clone-on-start: true
          default-label: main
          # This enables File System Backend
        native:
          search-locations: "[classpath:/, classpath:/config, classpath:/config/{application}, classpath:/config/{application}/{profile}]"

management:
  endpoints:
    web:
      exposure:
        include: busrefresh